src/Entity/MaterialsInWarehouse.php
<?php

namespace App\Entity;

use Symfony\Component\Validator\Constraints as Assert;
use App\Repository\MaterialsInWarehouseRepository;
use Doctrine\ORM\Mapping as ORM;

/**
 * @ORM\Entity(repositoryClass=MaterialsInWarehouseRepository::class)
 */
class MaterialsInWarehouse
{
    /**
     * @ORM\Id
     * @ORM\GeneratedValue
     * @ORM\Column(type="integer")
     */
    private $id;

    /**
     * @ORM\ManyToOne(targetEntity=WareHouses::class, inversedBy="materialsInWarehouses")
     */
    private $WareHouse;

    /**
     * @ORM\ManyToOne(targetEntity=Articles::class, inversedBy="materialsInWarehouses")
     */
    private $Article;

    /**
     * @ORM\Column(type="integer", nullable=true)
     * @Assert\Regex(
     * pattern="/^[1-9]\d*$/",
     * message="Liczba musi być większa od 0"
     * )
     */
    private $Amount;
    
    //  * @Assert\Regex("/^[0-9][0-9]?$|^100$/")

    /**
     * @ORM\Column(type="float", nullable=true)
     */
    private $VAT;

    /**
     * @ORM\Column(type="float")
     * @Assert\Regex("/^\d{0,8}(\.\d{1,4})?$/")
     */
    private $UnitPrice;

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getWareHouse(): ?WareHouses
    {
        return $this->WareHouse;
    }

    public function setWareHouse(?WareHouses $WareHouse): self
    {
        $this->WareHouse = $WareHouse;

        return $this;
    }

    public function getArticle(): ?Articles
    {
        return $this->Article;
    }

    public function setArticle(?Articles $Article): self
    {
        $this->Article = $Article;

        return $this;
    }

    public function getAmount(): ?int
    {
        return $this->Amount;
    }

    public function setAmount(?int $Amount): self
    {
        $this->Amount = $Amount;

        return $this;
    }

    public function getVAT(): ?float
    {
        return $this->VAT;
    }

    public function setVAT(?float $VAT): self
    {
        $this->VAT = $VAT;

        return $this;
    }

    public function getUnitPrice(): ?float
    {
        return $this->UnitPrice;
    }

    public function setUnitPrice(float $UnitPrice): self
    {
        $this->UnitPrice = $UnitPrice;

        return $this;
    }
}

src/Controller/WarehouseMaterialsController.php
<?php

namespace App\Controller;

use App\Entity\MaterialsInWarehouse;
use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;
use Symfony\Component\HttpFoundation\Request as HttpFoundationRequest;
use Symfony\Component\HttpFoundation\Response;
use Symfony\Component\Routing\Annotation\Route;
use Symfony\Component\Security\Core\User\UserInterface;

class WarehouseMaterialsController extends AbstractController
{
    /**
     * @Route("/warehousematerials", name="app_warehouse_materials")
     */
    public function index(HttpFoundationRequest $request, UserInterface $user): Response
    {
        $idUser = $user->getId();
        $materials = $this->getDoctrine()
            ->getRepository(MaterialsInWarehouse::class)->WarehouseFilterByUserId($user->getId());

        return $this->render('warehouse_materials/index.html.twig', [
            'materials' => $materials,
        ]);
    }
}

templates/warehouse_materials/index.html.twig
{% extends '@EasyAdmin/page/content.html.twig' %}

{% block title %}
	Stan Magazynowy
{% endblock %}
{% block content_title %}	Stan Magazynowy	{% endblock %}

{% block main %}

	<table class="table table-bordered table-stripped" id="sortTable">
		<thead>
			<tr>
				<th>Lp.</th>
				<th>Magazyn</th>
				<th>Artykuł</th>
				<th>Ilość</th>
				<th>Cena netto [zł]</th>
				<th>VAT [%]</th>
			</tr>
		</thead>
		<tbody>
        {% for key, material in materials %}
			<tr>
				<td>{{ key + 1 }}</td>
				<td>{{ material.warehouseName }}</td>
				<td>{{ material.article }}</td>
				<td>{{ material.amount }} {{ material.unit}} </td>
				<td>{{ material.price }}</td>
				<td>{{ material.vat * 100 }}</td>
			</tr>
        {% endfor %}
		</tbody>
	</head>
</table>
<script>
$('#sortTable').DataTable();
</script>
{% endblock %}